version: '3.8'

services:
  database:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: miappdb
    ports:
      - "5432:5432"
    networks:
      - miapp-network
    #volumes:
      #- postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    restart: always
    env_file: ./backend/.env
    depends_on:
      - database
    ports:
      - "3001:3001"
    networks:
      - miapp-network
    #volumes:
      #- ./backend:/app
      #- /app/node_modules 
    command: npm run start:dev 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-frontend
    restart: always
    #env_file: ./frontend/.env
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - miapp-network
    #volumes:
      #- ./frontend:/app
      #- /app/node_modules
    command: npm run dev

networks:
  miapp-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
